apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: connector-airgap-cert-secret
  name: connector-airgap
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: connector-airgap
  sessionAffinity: None
  type: ClusterIP
