apiVersion: v1
data:
  password: {{ .Values.GitServer.password | b64enc }}
  username: {{ .Values.GitServer.username | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secret
type: Opaque
