{{ $root := . }}
{{- range $Bundle := $root.Values.Bundles }}
apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: {{ $Bundle.name }}
spec:
  prereqs:
    repo: 'https://{{ $root.Release.Name }}.{{ $root.Release.Namespace }}.svc/git/{{ $root.Values.GitServer.repo }}'
    branch: master
    authSecret:
      name: {{ $root.Release.Name }}-auth-secret
    certSecret:
      name: {{ $root.Release.Name }}-cert-secret
    components:
      - name: deployment
        path: {{ $Bundle.paths.prereqs }}
        type: kustomize
        kustomization:
          images:
            - name: ibm-grpc-sample-connector
              newName: {{ $Bundle.images.microedge }}
              newTag: unreleased-main-latest
  instanced:
    repo: 'https://{{ $root.Release.Name }}.{{ $root.Release.Namespace }}.svc/git/{{ $root.Values.GitServer.repo }}'
    branch: master
    authSecret:
      name: {{ $root.Release.Name }}-auth-secret
    certSecret:
      name: {{ $root.Release.Name }}-cert-secret
    components:
      - name: connector
        path: {{ $Bundle.paths.instanced }}
        type: kustomize
        kustomization:
          images:
            - name: ibm-grpc-sample-connector
              newName: {{ $Bundle.images.local }}
              newTag: unreleased-main-latest
{{- end }}