apiVersion: v1
data:
  tls.conf: |
    LoadModule ssl_module modules/mod_ssl.so
    SSLEngine on
    SSLCertificateFile "/tls/tls.crt"
    SSLCertificateKeyFile "/tls/tls.key"
    SSLSessionCache "shmcb:/conf/ssl_gcache_data(512000)"
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server-config
