apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-cert-secret
  name: {{ .Release.Name }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
