kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aiopsedge-github-topology-integrator
subjects:
  - kind: ServiceAccount
    name: aiopsedge-github-topology-integrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aiopsedge-github-topology-integrator
