apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: connector-bridge
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connector-bridge
  targetCPUUtilizationPercentage: 80
