apiVersion: v1
kind: Service
metadata:
  name: connector-bridge
  annotations: 
    aiops.route.create.enabled: "true"
spec:
  selector:
    app: connector-bridge
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 8443
